name: formal

on:
  [push, workflow_dispatch]

jobs:
  formal:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r requirements.txt

      - name: install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3

      - name: fusesoc debug output
        run: |
          fusesoc list-cores
          fusesoc list-paths
          fusesoc core-info stevej_fifo

      - name: Run formal tests
        working-directory: ./src
        shell: bash
        run: |
          fusesoc --cores-root . run --target formal stevej_fifo
